import { Roboto } from "next/font/google";
import "./globals.css";
import React from "react";
import '@fontsource/roboto';
import ThemeRegistry from "./components/ThemeRegistry";

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <ThemeRegistry options={{ key: 'mui', mode: 'dark' }}>
        <body>
          {props.children}
        </body>
      </ThemeRegistry>
    </html>
  );
}
